### ISSUE TITLE
FormatException while parsing apache log

### ISSUE THREAD

**Issue by mi-schi** [tommy-muehle/error-log-parser#1]
I get a FormatException while parsing the apache log.

The invalid line is:
`[Tue Jun 21 14:56:32 2016] [warn] mod_fcgid: do nice things`

The pattern [client 1.2.3.4] is missing. 
Either the patterns are optional (I don't find a definition from the format of apache logs) or the parser define a entry model. There you only need one parser and set all patterns optional.

**Comment by tommy-muehle** [comment]
Thank you for the feedback, Michael. I changed the logic to fix your issue.
