### ISSUE TITLE
nginx error not parse to sentry

### ISSUE THREAD

**Issue by Naveenii** [tommy-muehle/error-log-parser#3]
Hello,

Nginx error log file not parse to sentry using sentry log pusher.

Parse the logfile and push it to sentry
=======================================

  [TM\ErrorLogParser\Exception\FormatException]
              The parser only supports the default Log-Format!

**Comment by tommy-muehle** [comment]
Hi @Naveenii,
could you please add some more informations to this issue? For example on which log entry this error occurs?

**Comment by Naveenii** [comment]
Hello Sir,

We are using linux server with nginx web server. We need to parse nginx error log file.

Please find the attach nginx error log file which we want to parse.
[error.zip](https://github.com/tommy-muehle/error-log-parser/files/1306251/error.zip)

Thanks
Naveen

**Comment by Naveenii** [comment]
Hello Sir,

We are using linux server with nginx web server. We need to parse nginx error log file.

Please find the attach nginx error log file which we want to parse.
error.zip

Thanks
Naveen

**Comment by Naveenii** [comment]
Hello Sir,

We are using linux server with nginx web server. We need to parse nginx error log file.

Please find the attach nginx error log file which we want to parse.
error.zip

Thanks
Naveen
[error.zip](https://github.com/tommy-muehle/error-log-parser/files/1306305/error.zip)

**Comment by tommy-muehle** [comment]
Hi @Naveenii,

I take a look over your logfile and tested two lines with the nginx log-parser without problems.
For example:

**Line** 
2017/09/13 18:02:00 [error] 1448#0: *23087 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method articles_type_model::get_categories() in /home/web/fuzianewtest/website/application/controllers/Articles.php on line 2250" while reading response header from upstream, client: 192.168.1.12, server: fuzianewtest.ii.com, request: "GET /articles/articles_add/page_no/0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-fuzianewtest.socket:", host: "fuzianewtest.ii.com"

**Result:**
```
class stdClass#25 (7) {
  public $date =>
  string(19) "2017/09/13 18:02:00"
  public $type =>
  string(5) "error"
  public $message =>
  string(254) "*23087 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method articles_type_model::get_categories() in /home/web/fuzianewtest/website/application/controllers/Articles.php on line 2250" while reading response header from upstream"
  public $client =>
  string(12) "192.168.1.12"
  public $server =>
  string(19) "fuzianewtest.ii.com"
  public $request =>
  string(45) "GET /articles/articles_add/page_no/0 HTTP/1.1"
  public $host =>
  string(19) "fuzianewtest.ii.com"
}
```

So maybe you can give me the concrete line which results in an error? Otherwise you can also test the FormlessParser.

**Comment by Naveenii** [comment]
Hi @Tommy-muehle,

We are facing same issue when use below mention log

2017/09/13 18:02:00 [error] 1448#0: *23087 FastCGI sent in stderr: "PHP message: PHP Fatal error: Call to undefined method articles_type_model::get_categories() in /home/web/fuzianewtest/website/application/controllers/Articles.php on line 2250" while reading response header from upstream, client: 192.168.1.12, server: fuzianewtest.ii.com, request: "GET /articles/articles_add/page_no/0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-fuzianewtest.socket:", host: "fuzianewtest.ii.com"

## Received below error message:

Parse the logfile and push it to sentry
=======================================

  [TM\ErrorLogParser\Exception\FormatException]
              The parser only supports the default Log-Format!
              If you think this is an error please refer to
              https://github.com/tommy-muehle/error-log-parser/issues
              and create an issue!

push [-s|--logfile-type [LOGFILE-TYPE]] [-t|--log-type [LOG-TYPE]] [-d|--sentry-dsn SENTRY-DSN] [--] <logfile>

And how we can use --logfile-type [LOGFILE-TYPE]] [-t|--log-type option.

Thanks
Naveen

**Comment by Naveenii** [comment]
We are facing same issue when use below mention log

PHP message: PHP Fatal error:  Using $this when not in object context in /home/web/fuzianewtest/website/application/config/config.php on line 7
PHP message: PHP Notice:  Undefined index: HTTPS in /home/web/fuzianewtest/website/application/config/config.php on line 5
PHP message: PHP Fatal error:  Using $this when not in object context in /home/web/fuzianewtest/website/application/config/config.php on line 7" while reading response header from upstream, client: 192.168.1.12, server: fuzianewtest.ii.com, request: "GET /home HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-fuzianewtest.socket:", host: "fuzianewtest.ii.com"
2017/09/18 15:03:03 [error] 3934#0: *1231 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: HTTPS in /home/web/fuzianewtest/website/application/config/config.php on line 5
PHP message: PHP Fatal error:  Using $this when not in object context in /home/web/fuzianewtest/website/application/config/config.php on line 7
PHP message: PHP Notice:  Undefined index: HTTPS in /home/web/fuzianewtest/website/application/config/config.php on line 5
PHP message: PHP Fatal error:  Using $this when not in object context in /home/web/fuzianewtest/website/application/config/config.php on line 7" while reading response header from upstream, client: 192.168.1.12, server: fuzianewtest.ii.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-fuzianewtest.socket:", host: "fuzianewtest.ii.com"

Received below error message:

Parse the logfile and push it to sentry

[TM\ErrorLogParser\Exception\FormatException]
The parser only supports the default Log-Format!
If you think this is an error please refer to
https://github.com/tommy-muehle/error-log-parser/issues
and create an issue!

push [-s|--logfile-type [LOGFILE-TYPE]] [-t|--log-type [LOG-TYPE]] [-d|--sentry-dsn SENTRY-DSN] [--]

And how we can use --logfile-type [LOGFILE-TYPE]] [-t|--log-type option.

Thanks
Naveen

**Comment by tommy-muehle** [comment]
I’m closing this issue because it has been inactive for a few years. Please reopen if you still encounter this issue.

Thank you!
